---
  - name: create allow rules for all hosts
    ufw:
      rule: allow
      proto: any
      src: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
    with_inventory_hostnames:
      - all
