---
  - name: Make sure apt-get is up to date
    raw: apt-get update
    
  - name: 'install python2'
    raw: sudo apt-get -y install python-simplejson

  - name: Install aptitude
    apt:
      name: aptitude
      state: present

  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes

  - name: Gathering facts
    setup:

  - name: Set hostname
    lineinfile: dest=/etc/hosts line="127.0.0.1 {{ansible_hostname}}"

  - name: Install ufw
    apt: name=ufw state=present

  - name: create a new user
    user: name={{ newuser }}
          state=present
          shell=/bin/bash

  - authorized_key: user="{{ newuser }}"
                    key="{{ lookup('file', ssh_key ) }}"

  - name: Make sure we can sudo
    template: src=newuser_sudoer dest=/etc/sudoers.d/{{ newuser }}_sudoer mode=0440

  - name: Configure ufw
    ufw: rule=allow port=22 proto=tcp

  - name: Default deny
    ufw: state=enabled direction=incoming policy=deny

  - name: Disable root SSH
    copy: src=sshd_config dest=/etc/ssh/sshd_config

  - name: Restart SSH
    service: name=ssh state=restarted enabled=yes